name: SyncWeather
version: @version@
main: com.github.aiczk.syncweather.SyncWeather
api-version: 1.16
authors: [ aiczk ]
description: A plug-in that matches the local weather in Japan with the weather in Minecraft.

commands:
  UpdateWeather:
    usage: get-json
  SetWeatherLocale:
    usage: set locale