package com.github.aiczk.syncweather.command.json

import kotlinx.serialization.Serializable

@Serializable
data class Preall(
    val day: Int,
    val hour: Int,
    val minute: Int,
    val month: Int,
    val precip_12h: Double,
    val precip_12h_daily_max: Double,
    val precip_12h_daily_max_q: Double,
    val precip_12h_new_record_in_decade: Double?,
    val precip_12h_new_record_month: Double?,
    val precip_12h_q: Double,
    val precip_1h: Double,
    val precip_1h_daily_max: Double,
    val precip_1h_daily_max_q: Double,
    val precip_1h_new_record_in_decade: Double?,
    val precip_1h_new_record_month: Double?,
    val precip_1h_q: Double,
    val precip_24h: Double,
    val precip_24h_daily_max: Double,
    val precip_24h_daily_max_q: Double,
    val precip_24h_new_record_in_decade: Double?,
    val precip_24h_new_record_month: Double?,
    val precip_24h_q: Double,
    val precip_3h: Double,
    val precip_3h_daily_max: Double,
    val precip_3h_daily_max_q: Double,
    val precip_3h_new_record_in_decade: Double?,
    val precip_3h_new_record_month: Double?,
    val precip_3h_q: Double,
    val precip_48h: Double,
    val precip_48h_daily_max: Double,
    val precip_48h_daily_max_q: Double,
    val precip_48h_new_record_in_decade: Double?,
    val precip_48h_new_record_month: Double?,
    val precip_48h_q: Double,
    val precip_6h: Double,
    val precip_6h_daily_max: Double,
    val precip_6h_daily_max_q: Double,
    val precip_6h_new_record_in_decade: Double?,
    val precip_6h_new_record_month: Double?,
    val precip_6h_q: Double,
    val precip_72h: Double,
    val precip_72h_daily_max: Double,
    val precip_72h_daily_max_q: Double,
    val precip_72h_new_record_in_decade: Double?,
    val precip_72h_new_record_month: Double?,
    val precip_72h_q: Double,
    val precip_daily: Double,
    val precip_daily_new_record_in_decade: Double?,
    val precip_daily_new_record_month: Double?,
    val precip_daily_q: Double,
    val updatedAt: String,
    val year: Int
)