package com.github.aiczk.syncweather.command.json

import kotlinx.serialization.Serializable

@Serializable
data class Preall(
    val day: Int,
    val hour: Int,
    val minute: Int,
    val month: Int,
    val precip_12h: Int,
    val precip_12h_daily_max: Int,
    val precip_12h_daily_max_q: Int,
    val precip_12h_new_record_in_decade: Int?,
    val precip_12h_new_record_month: Int?,
    val precip_12h_q: Int,
    val precip_1h: Int,
    val precip_1h_daily_max: Int,
    val precip_1h_daily_max_q: Int,
    val precip_1h_new_record_in_decade: Int?,
    val precip_1h_new_record_month: Int?,
    val precip_1h_q: Int,
    val precip_24h: Int,
    val precip_24h_daily_max: Double,
    val precip_24h_daily_max_q: Int,
    val precip_24h_new_record_in_decade: Int?,
    val precip_24h_new_record_month: Int?,
    val precip_24h_q: Int,
    val precip_3h: Int,
    val precip_3h_daily_max: Int,
    val precip_3h_daily_max_q: Int,
    val precip_3h_new_record_in_decade: Int?,
    val precip_3h_new_record_month: Int?,
    val precip_3h_q: Int,
    val precip_48h: Int,
    val precip_48h_daily_max: Int,
    val precip_48h_daily_max_q: Int,
    val precip_48h_new_record_in_decade: Int?,
    val precip_48h_new_record_month: Int?,
    val precip_48h_q: Int,
    val precip_6h: Int,
    val precip_6h_daily_max: Int,
    val precip_6h_daily_max_q: Int,
    val precip_6h_new_record_in_decade: Int?,
    val precip_6h_new_record_month: Int?,
    val precip_6h_q: Int,
    val precip_72h: Int,
    val precip_72h_daily_max: Int,
    val precip_72h_daily_max_q: Int,
    val precip_72h_new_record_in_decade: Int?,
    val precip_72h_new_record_month: Int?,
    val precip_72h_q: Int,
    val precip_daily: Int,
    val precip_daily_new_record_in_decade: Int?,
    val precip_daily_new_record_month: Int?,
    val precip_daily_q: Int,
    val updatedAt: String,
    val year: Int
)